//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_zapasow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzytkownik()
        {
            this.Wypozyczenie = new HashSet<Wypozyczenie>();
        }
    
        public int Uzytkownik_Id { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Adres { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Miasto { get; set; }
        public string Dowod { get; set; }
        public string Nr_telefonu { get; set; }
        public string ImieNazwisko
        {
            get
            {
                return Imie + " " + Nazwisko;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenie> Wypozyczenie { get; set; }
    }
}
