//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_zapasow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie
    {
        public int Wypozyczenie_Id { get; set; }
        public Nullable<int> Zgloszenie { get; set; }
        public System.DateTime Data_wypozyczenia { get; set; }
        public System.DateTime Data_zwrotu { get; set; }
        public int Uzytkownik_Id { get; set; }
        public string Nr_stacji { get; set; }
        public bool Zwrot { get; set; }
    
        public virtual Stacje Stacje { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
