//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_zapasow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WypozyczenieTV
    {
        public int WypozyczenieTVID { get; set; }
        public Nullable<System.DateTime> DataWypozyczenia { get; set; }
        public Nullable<System.DateTime> DataZwrotu { get; set; }
        public Nullable<int> TelewizorID { get; set; }
        public string Dodatkowo { get; set; }
        public string Opis { get; set; }
    
        public virtual Telewizory Telewizory { get; set; }
    }
}
