//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_zapasow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zapasy_bazaEntities : DbContext
    {
        public Zapasy_bazaEntities()
            : base("name=Zapasy_bazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rodzaje_stacji> Rodzaje_stacji { get; set; }
        public virtual DbSet<Stacje> Stacje { get; set; }
        public virtual DbSet<Uzytkownik> Uzytkownik { get; set; }
        public virtual DbSet<Wypozyczenie> Wypozyczenie { get; set; }
        public virtual DbSet<Telewizory> Telewizory { get; set; }
        public virtual DbSet<WypozyczenieTV> WypozyczenieTV { get; set; }
    }
}
